// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTzMxDVoebkzUfYgRKFAiu7sLfMYryjJk',
    appId: '1:178831669451:web:9994ae519a6d746e7d434e',
    messagingSenderId: '178831669451',
    projectId: 'notes-app-18610',
    authDomain: 'notes-app-18610.firebaseapp.com',
    storageBucket: 'notes-app-18610.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9OkP0XPc0E_8lXZ82jvuFLIslyL-CC7M',
    appId: '1:178831669451:android:e873d5af7bd60d1e7d434e',
    messagingSenderId: '178831669451',
    projectId: 'notes-app-18610',
    storageBucket: 'notes-app-18610.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvzdhCN42Xw_Ik5g_xqS25O-CL17tuOiU',
    appId: '1:178831669451:ios:36f93706999d587d7d434e',
    messagingSenderId: '178831669451',
    projectId: 'notes-app-18610',
    storageBucket: 'notes-app-18610.appspot.com',
    iosClientId: '178831669451-5e79mim087541v3uuldddged9v6iafmr.apps.googleusercontent.com',
    iosBundleId: 'com.example.notesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvzdhCN42Xw_Ik5g_xqS25O-CL17tuOiU',
    appId: '1:178831669451:ios:c126507a89f0980b7d434e',
    messagingSenderId: '178831669451',
    projectId: 'notes-app-18610',
    storageBucket: 'notes-app-18610.appspot.com',
    iosClientId: '178831669451-uikihkbblbjdmh95udu2c610v6c7k169.apps.googleusercontent.com',
    iosBundleId: 'com.example.notesApp.RunnerTests',
  );
}
